-- MySQL Script generated by MySQL Workbench
-- 11/22/16 23:33:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gimnasio
-- -----------------------------------------------------
-- Base de datos para el proyecto de ADOO

-- -----------------------------------------------------
-- Schema gimnasio
--
-- Base de datos para el proyecto de ADOO
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gimnasio` DEFAULT CHARACTER SET utf8 ;
USE `gimnasio` ;

-- -----------------------------------------------------
-- Table `gimnasio`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Estado` (
  `idEstado` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Direccion` (
  `idDireccion` INT NOT NULL,
  `Calle` VARCHAR(45) NULL,
  `Colonia` VARCHAR(45) NULL,
  `numExt` INT(6) NULL,
  `Deleg_Mun` VARCHAR(45) NULL,
  `CodePostal` INT(6) NULL,
  `NumInt` INT(6) NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idDireccion`, `Estado_idEstado`),
  INDEX `fk_Direccion_Estado1_idx` (`Estado_idEstado` ASC),
  CONSTRAINT `fk_Direccion_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `gimnasio`.`Estado` (`idEstado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Sucursal` (
  `idSucursal` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Inauguracion` DATE NOT NULL,
  `Latitud` FLOAT NOT NULL,
  `Longitud` FLOAT NOT NULL,
  `Direccion_idDireccion` INT NOT NULL,
  `Direccion_Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idSucursal`),
  INDEX `fk_Sucursal_Direccion1_idx` (`Direccion_idDireccion` ASC, `Direccion_Estado_idEstado` ASC),
  CONSTRAINT `fk_Sucursal_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion` , `Direccion_Estado_idEstado`)
    REFERENCES `gimnasio`.`Direccion` (`idDireccion` , `Estado_idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Areas` (
  `idAreas` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `TipoArea` VARCHAR(45) NULL,
  `Largo` FLOAT NULL,
  `Ancho` FLOAT NULL,
  `Capacidad` INT(3) NULL,
  `Descripcion` VARCHAR(500) NULL,
  PRIMARY KEY (`idAreas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Cursos` (
  `idCursos` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Costo` FLOAT NULL,
  `FechaInicio` DATE NULL,
  `FechaTermino` DATE NULL,
  `Descripcion` VARCHAR(500) NULL,
  `Horario` DATE NULL,
  PRIMARY KEY (`idCursos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Membresia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Membresia` (
  `idMembresia` VARCHAR(20) NOT NULL,
  `Costo` FLOAT NULL,
  `FechaCompra` DATE NULL,
  `FechaCaduca` DATE NULL,
  PRIMARY KEY (`idMembresia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `ApellidoP` VARCHAR(45) NULL,
  `ApellidoM` VARCHAR(45) NULL,
  `CURP` VARCHAR(45) NULL,
  `FechaNacim` DATE NULL,
  `CuentaActiva` ENUM('Activo', 'No activo') NULL,
  `Membresia_idMembresia` VARCHAR(20) NOT NULL,
  `Direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fk_Cliente_Membresia1_idx` (`Membresia_idMembresia` ASC),
  INDEX `fk_Cliente_Direccion1_idx` (`Direccion_idDireccion` ASC),
  CONSTRAINT `fk_Cliente_Membresia1`
    FOREIGN KEY (`Membresia_idMembresia`)
    REFERENCES `gimnasio`.`Membresia` (`idMembresia`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_Cliente_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `gimnasio`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Instructor` (
  `idInstructor` INT NOT NULL,
  `Direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idInstructor`, `Direccion_idDireccion`),
  INDEX `fk_Instructor_Direccion1_idx` (`Direccion_idDireccion` ASC),
  CONSTRAINT `fk_Instructor_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `gimnasio`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`PersonalVentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`PersonalVentas` (
  `idPersonalVentas` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `ApellidoP` VARCHAR(45) NULL,
  `ApellidoM` VARCHAR(45) NULL,
  `CURP` VARCHAR(45) NULL,
  `NSS` VARCHAR(45) NULL,
  `FechaIngreso` DATE NULL,
  `FechaFinContrato` DATE NULL,
  `FechaNacim` DATE NULL,
  `TipoEmpleado` ENUM('Recepcionista', 'Ejec Ventas') NULL,
  PRIMARY KEY (`idPersonalVentas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Servicios` (
  `idServicios` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Costo` FLOAT NULL,
  `Descripcion` VARCHAR(200) NULL,
  `Horario` DATETIME NULL,
  `EstadoServicio` ENUM('Activo', 'Inactivo') NULL,
  `Ubicacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idServicios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Emails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Emails` (
  `Sucursal_idSucursal` INT NOT NULL,
  `email` VARCHAR(90) NULL,
  PRIMARY KEY (`Sucursal_idSucursal`),
  CONSTRAINT `fk_Emails_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `gimnasio`.`Sucursal` (`idSucursal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Deleg_Mun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Deleg_Mun` (
  `idDeleg_Mun` INT NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idDeleg_Mun`, `Estado_idEstado`),
  INDEX `fk_Deleg_Mun_Estado1_idx` (`Estado_idEstado` ASC),
  CONSTRAINT `fk_Deleg_Mun_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `gimnasio`.`Estado` (`idEstado`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`DatosMedicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`DatosMedicos` (
  `idClienteEmpleado` INT NOT NULL,
  `Tipo_Sangre` ENUM('A', 'B', 'AB', 'O') NULL,
  `Enfermedades` VARCHAR(145) NULL,
  `Peso` FLOAT NULL,
  `Altura` FLOAT NULL,
  `CondicionMedica` VARCHAR(500) NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idClienteEmpleado`, `Cliente_idCliente`),
  INDEX `fk_DatosMedicos_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_DatosMedicos_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `gimnasio`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Gerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Gerente` (
  `idGerente` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `ApellidoP` VARCHAR(45) NULL,
  `ApellidoM` VARCHAR(45) NULL,
  `CURP` VARCHAR(45) NULL,
  `FechaNAcim` DATE NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  `Direccion_idDireccion` INT NOT NULL,
  PRIMARY KEY (`idGerente`, `Sucursal_idSucursal`),
  INDEX `fk_Gerente_Sucursal1_idx` (`Sucursal_idSucursal` ASC),
  INDEX `fk_Gerente_Direccion1_idx` (`Direccion_idDireccion` ASC),
  CONSTRAINT `fk_Gerente_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `gimnasio`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Gerente_Direccion1`
    FOREIGN KEY (`Direccion_idDireccion`)
    REFERENCES `gimnasio`.`Direccion` (`idDireccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Usuario` (
  `idUsuario` INT NOT NULL,
  ` Nombre` VARCHAR(45) NULL,
  `ApellidoP` VARCHAR(45) NULL,
  `ApellidoM` VARCHAR(45) NULL,
  `CURP` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`TarjetaCredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`TarjetaCredito` (
  `idTarjetaCredito` INT NOT NULL,
  `Vencimiento` DATE NULL,
  `Cliente_idCliente` INT NOT NULL,
  PRIMARY KEY (`idTarjetaCredito`, `Cliente_idCliente`),
  INDEX `fk_TarjetaCredito_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_TarjetaCredito_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `gimnasio`.`Cliente` (`idCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Areas_has_Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Areas_has_Cursos` (
  `Areas_idAreas` INT NOT NULL,
  `Cursos_idCursos` INT NOT NULL,
  PRIMARY KEY (`Areas_idAreas`, `Cursos_idCursos`),
  INDEX `fk_Areas_has_Cursos_Cursos1_idx` (`Cursos_idCursos` ASC),
  INDEX `fk_Areas_has_Cursos_Areas1_idx` (`Areas_idAreas` ASC),
  CONSTRAINT `fk_Areas_has_Cursos_Areas1`
    FOREIGN KEY (`Areas_idAreas`)
    REFERENCES `gimnasio`.`Areas` (`idAreas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Areas_has_Cursos_Cursos1`
    FOREIGN KEY (`Cursos_idCursos`)
    REFERENCES `gimnasio`.`Cursos` (`idCursos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Sucursal_has_Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Sucursal_has_Cursos` (
  `Sucursal_idSucursal` INT NOT NULL,
  `Cursos_idCursos` INT NOT NULL,
  PRIMARY KEY (`Sucursal_idSucursal`, `Cursos_idCursos`),
  INDEX `fk_Sucursal_has_Cursos_Cursos1_idx` (`Cursos_idCursos` ASC),
  INDEX `fk_Sucursal_has_Cursos_Sucursal1_idx` (`Sucursal_idSucursal` ASC),
  CONSTRAINT `fk_Sucursal_has_Cursos_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `gimnasio`.`Sucursal` (`idSucursal`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Sucursal_has_Cursos_Cursos1`
    FOREIGN KEY (`Cursos_idCursos`)
    REFERENCES `gimnasio`.`Cursos` (`idCursos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Instructor_imparte_Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Instructor_imparte_Cursos` (
  `Instructor_idInstructor` INT NOT NULL,
  `Cursos_idCursos` INT NOT NULL,
  `HorarioInicio` DATETIME NOT NULL,
  `HorarioTermino` DATETIME NOT NULL,
  PRIMARY KEY (`Instructor_idInstructor`, `Cursos_idCursos`),
  INDEX `fk_Instructor_has_Cursos_Cursos1_idx` (`Cursos_idCursos` ASC),
  INDEX `fk_Instructor_has_Cursos_Instructor1_idx` (`Instructor_idInstructor` ASC),
  CONSTRAINT `fk_Instructor_has_Cursos_Instructor1`
    FOREIGN KEY (`Instructor_idInstructor`)
    REFERENCES `gimnasio`.`Instructor` (`idInstructor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Instructor_has_Cursos_Cursos1`
    FOREIGN KEY (`Cursos_idCursos`)
    REFERENCES `gimnasio`.`Cursos` (`idCursos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Usuario_accede_Areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Usuario_accede_Areas` (
  `Areas_idAreas` INT NOT NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `TiempoEstadia` INT NULL,
  PRIMARY KEY (`Areas_idAreas`, `Usuario_idUsuario`),
  INDEX `fk_Areas_has_Usuario_Usuario1_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Areas_has_Usuario_Areas1_idx` (`Areas_idAreas` ASC),
  CONSTRAINT `fk_Areas_has_Usuario_Areas1`
    FOREIGN KEY (`Areas_idAreas`)
    REFERENCES `gimnasio`.`Areas` (`idAreas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Areas_has_Usuario_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `gimnasio`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Membresia_has_Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Membresia_has_Servicios` (
  `Membresia_idMembresia` VARCHAR(20) NOT NULL,
  `Servicios_idServicios` INT NOT NULL,
  PRIMARY KEY (`Membresia_idMembresia`, `Servicios_idServicios`),
  INDEX `fk_Membresia_has_Servicios_Servicios1_idx` (`Servicios_idServicios` ASC),
  INDEX `fk_Membresia_has_Servicios_Membresia1_idx` (`Membresia_idMembresia` ASC),
  CONSTRAINT `fk_Membresia_has_Servicios_Membresia1`
    FOREIGN KEY (`Membresia_idMembresia`)
    REFERENCES `gimnasio`.`Membresia` (`idMembresia`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Membresia_has_Servicios_Servicios1`
    FOREIGN KEY (`Servicios_idServicios`)
    REFERENCES `gimnasio`.`Servicios` (`idServicios`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Usuario_usa_Servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Usuario_usa_Servicios` (
  `Usuario_idUsuario` INT NOT NULL,
  `Servicios_idServicios` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Servicios_idServicios`),
  INDEX `fk_Usuario_has_Servicios_Servicios1_idx` (`Servicios_idServicios` ASC),
  INDEX `fk_Usuario_has_Servicios_Usuario1_idx` (`Usuario_idUsuario` ASC),
  CONSTRAINT `fk_Usuario_has_Servicios_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `gimnasio`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Servicios_Servicios1`
    FOREIGN KEY (`Servicios_idServicios`)
    REFERENCES `gimnasio`.`Servicios` (`idServicios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Sucursal_has_PersonalVentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Sucursal_has_PersonalVentas` (
  `Sucursal_idSucursal` INT NOT NULL,
  `PersonalVentas_idPersonalVentas` INT NOT NULL,
  `FechaIngreso` DATE NULL,
  `FechaTermino` DATE NULL,
  PRIMARY KEY (`Sucursal_idSucursal`, `PersonalVentas_idPersonalVentas`),
  INDEX `fk_Sucursal_has_PersonalVentas_PersonalVentas1_idx` (`PersonalVentas_idPersonalVentas` ASC),
  INDEX `fk_Sucursal_has_PersonalVentas_Sucursal1_idx` (`Sucursal_idSucursal` ASC),
  CONSTRAINT `fk_Sucursal_has_PersonalVentas_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `gimnasio`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_has_PersonalVentas_PersonalVentas1`
    FOREIGN KEY (`PersonalVentas_idPersonalVentas`)
    REFERENCES `gimnasio`.`PersonalVentas` (`idPersonalVentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Personal_vende_Membresia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Personal_vende_Membresia` (
  `PersonalVentas_idPersonalVentas` INT NOT NULL,
  `Membresia_idMembresia` VARCHAR(20) NOT NULL,
  `Fecha venta` DATE NULL,
  `FormaPago` ENUM('Tarjeta', 'Efectivo') NULL,
  `CostoMembresia` DECIMAL(5,2) NULL,
  PRIMARY KEY (`PersonalVentas_idPersonalVentas`, `Membresia_idMembresia`),
  INDEX `fk_PersonalVentas_has_Membresia_Membresia1_idx` (`Membresia_idMembresia` ASC),
  INDEX `fk_PersonalVentas_has_Membresia_PersonalVentas1_idx` (`PersonalVentas_idPersonalVentas` ASC),
  CONSTRAINT `fk_PersonalVentas_has_Membresia_PersonalVentas1`
    FOREIGN KEY (`PersonalVentas_idPersonalVentas`)
    REFERENCES `gimnasio`.`PersonalVentas` (`idPersonalVentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PersonalVentas_has_Membresia_Membresia1`
    FOREIGN KEY (`Membresia_idMembresia`)
    REFERENCES `gimnasio`.`Membresia` (`idMembresia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Telefonos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Telefonos` (
  `Numero` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Numero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Sucursal_has_Telefonos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Sucursal_has_Telefonos` (
  `Sucursal_idSucursal` INT NOT NULL,
  `Telefonos_Numero` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Sucursal_idSucursal`, `Telefonos_Numero`),
  INDEX `fk_Sucursal_has_Telefonos_Telefonos1_idx` (`Telefonos_Numero` ASC),
  INDEX `fk_Sucursal_has_Telefonos_Sucursal1_idx` (`Sucursal_idSucursal` ASC),
  CONSTRAINT `fk_Sucursal_has_Telefonos_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `gimnasio`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sucursal_has_Telefonos_Telefonos1`
    FOREIGN KEY (`Telefonos_Numero`)
    REFERENCES `gimnasio`.`Telefonos` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gimnasio`.`Cliente_has_Telefonos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gimnasio`.`Cliente_has_Telefonos` (
  `Cliente_idCliente` INT NOT NULL,
  `Telefonos_Numero` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`Cliente_idCliente`, `Telefonos_Numero`),
  INDEX `fk_Cliente_has_Telefonos_Telefonos1_idx` (`Telefonos_Numero` ASC),
  INDEX `fk_Cliente_has_Telefonos_Cliente1_idx` (`Cliente_idCliente` ASC),
  CONSTRAINT `fk_Cliente_has_Telefonos_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `gimnasio`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Telefonos_Telefonos1`
    FOREIGN KEY (`Telefonos_Numero`)
    REFERENCES `gimnasio`.`Telefonos` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `gimnasio`.`Estado`
-- -----------------------------------------------------
START TRANSACTION;
USE `gimnasio`;
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (1, 'Aguascalientes');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (2, 'Baja California');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (3, 'Baja California Sur');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (4, 'Campeche');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (5, 'Coahuila');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (6, 'Colima');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (7, 'Chiapas');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (8, 'Chihuahua');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (9, 'Ciudad de México');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (10, 'Durango');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (11, 'Guanajuato');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (12, 'Guerrero');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (13, 'Hidalgo');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (14, 'Jalisco');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (15, 'Estado de México');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (16, 'Michoacán');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (17, 'Morelos');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (18, 'Nayarit');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (19, 'Nuevo León');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (20, 'Oaxaca');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (21, 'Puebla');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (22, 'Querétaro');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (23, 'Quintana Roo');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (24, 'San Luis Potosí');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (25, 'Sinaloa');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (26, 'Sonora');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (27, 'Tabasco');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (28, 'Tamaulipas');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (29, 'Tlaxcala');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (30, 'Veracruz');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (31, 'Yucatán');
INSERT INTO `gimnasio`.`Estado` (`idEstado`, `Nombre`) VALUES (32, 'Zacatecas');

COMMIT;


-- -----------------------------------------------------
-- Data for table `gimnasio`.`Deleg_Mun`
-- -----------------------------------------------------
START TRANSACTION;
USE `gimnasio`;
INSERT INTO `gimnasio`.`Deleg_Mun` (`idDeleg_Mun`, `Estado_idEstado`, `Nombre`) VALUES (1, 9, 'Álvaro Obregón');
INSERT INTO `gimnasio`.`Deleg_Mun` (`idDeleg_Mun`, `Estado_idEstado`, `Nombre`) VALUES (2, 9, 'Azcapotzalco');
INSERT INTO `gimnasio`.`Deleg_Mun` (`idDeleg_Mun`, `Estado_idEstado`, `Nombre`) VALUES (3, 9, 'Benito Juárez');
INSERT INTO `gimnasio`.`Deleg_Mun` (`idDeleg_Mun`, `Estado_idEstado`, `Nombre`) VALUES (4, 9, 'Coyoacán');
INSERT INTO `gimnasio`.`Deleg_Mun` (`idDeleg_Mun`, `Estado_idEstado`, `Nombre`) VALUES (5, 9, 'Cuajimalpa');
INSERT INTO `gimnasio`.`Deleg_Mun` (`idDeleg_Mun`, `Estado_idEstado`, `Nombre`) VALUES (6, 9, 'Cuauhtémoc');
INSERT INTO `gimnasio`.`Deleg_Mun` (`idDeleg_Mun`, `Estado_idEstado`, `Nombre`) VALUES (7, 9, 'Gustavo A. Madero');
INSERT INTO `gimnasio`.`Deleg_Mun` (`idDeleg_Mun`, `Estado_idEstado`, `Nombre`) VALUES (8, 9, 'Iztacalco');
INSERT INTO `gimnasio`.`Deleg_Mun` (`idDeleg_Mun`, `Estado_idEstado`, `Nombre`) VALUES (9, 9, 'Iztapalapa');
INSERT INTO `gimnasio`.`Deleg_Mun` (`idDeleg_Mun`, `Estado_idEstado`, `Nombre`) VALUES (10, 9, 'Magdalena Contreras');
INSERT INTO `gimnasio`.`Deleg_Mun` (`idDeleg_Mun`, `Estado_idEstado`, `Nombre`) VALUES (11, 9, 'Miguel Hidalgo');
INSERT INTO `gimnasio`.`Deleg_Mun` (`idDeleg_Mun`, `Estado_idEstado`, `Nombre`) VALUES (12, 9, 'Milpa Alta');
INSERT INTO `gimnasio`.`Deleg_Mun` (`idDeleg_Mun`, `Estado_idEstado`, `Nombre`) VALUES (13, 9, 'Tláhuac');
INSERT INTO `gimnasio`.`Deleg_Mun` (`idDeleg_Mun`, `Estado_idEstado`, `Nombre`) VALUES (14, 9, 'Tlalpan');
INSERT INTO `gimnasio`.`Deleg_Mun` (`idDeleg_Mun`, `Estado_idEstado`, `Nombre`) VALUES (15, 9, 'Venustiano Carranza');
INSERT INTO `gimnasio`.`Deleg_Mun` (`idDeleg_Mun`, `Estado_idEstado`, `Nombre`) VALUES (16, 9, 'Xochimilco');

COMMIT;

